global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Spring BootアプリケーションがホストしているURL
    metrics_path: '/actuator/prometheus'  # Spring Boot ActuatorのPrometheusエンドポイント