logging:
  level:
    org.springframework.boot.actuate.metrics: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    server:
      request:
        include: "*"